apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-service-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-service-admin-binding
subjects:
  - kind: ServiceAccount
    name: pod-service-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-service
  template:
    metadata:
      labels:
        app: pod-service
    spec:
      serviceAccountName: pod-service-sa
      containers:
        - name: pod-service
          image: ahmadibraspectrocloud/pod-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          command: ["/bin/sh"]
          args: ["-c", "/pod-service"]

---
apiVersion: v1
kind: Service
metadata:
  name: pod-service
spec:
  selector:
    app: pod-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

